### ISSUE TITLE
Is MSE estimation in assignment 1 valid?

### ISSUE THREAD

**Issue by aorazalin** [statwangz/MATH-4432-Statistical-Machine-Learning#2]
I was a bit confused at the code snippet when doing homework 1. Estimation of the linear | KNN models' bias & variance involved putting noise on top of the response $y$ a bunch of times, training the model on that "sample" & saving the prediction to later evaluate and average out. 

But from lecture notes & the wiki page it seems like both bias and the variance are expectations of _some term_ given X (predictors) - being random. Thus, I expected X to be sampled `nrep` times instead of putting noise on y `nrep` times. I don't get where am I wrong here. Thank you.

**Comment by statwangz** [comment]
Good question!
Typically, we should sample `X` `nrep` times to get `nrep` different training sets. Note that the training set consists of two parts: `X` and `y_obs`. Here we simplify the evaluation scheme. We fix `X` and get true `y`, then add noise `nrep` times to get `nrep` different `y_obs`. `X` and `nrep` different `y_obs` consist `nrep` different training sets. Since overfitting always comes from noise, the fitted model will vary based on different noise added. Therefore, we can observe the bias-variance trade-off pattern we want to see.

Best,
Zhiwei

**Comment by aorazalin** [comment]
Oh, I see. It's just a simplification then. Thank you for your answer!
